block-list-secret-scan: []
branch: master
compact: true
directory:
  - ./
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - all
mask: []
output:
  - cli
  - junitxml
output-file-path: console,checkov.test.xml
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_DOCKER_2 # Container Healthcheck
  - CKV_DOCKER_3 # Container user
  - CKV_AWS_158 # Cloudwatch encrypted
  - CKV_AWS_116 # Lambda DLQ
  - CKV_AWS_117 # Lambda VPC
  - CKV_AWS_136 # ECR KMS
  - CKV_AWS_51 # ECR Immutable
  - CKV_AWS_173 # Lambda Env Encrypted
  - CKV_AWS_115 # Lambda Concurrent
  - CKV_AWS_18 # @TODO enable S3 access logs
  - CKV_AWS_195 # Athena view Security
skip-download: true
summary-position: bottom
